# Generated by Django 3.0.5 on 2023-11-28 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='getFecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaModelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=255)),
                ('objetivo', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('tema_central', models.CharField(max_length=255)),
                ('tema_semanal', models.CharField(max_length=255)),
                ('periodo', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'metas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=255)),
                ('subtema', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'temas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('material', models.CharField(max_length=255)),
                ('cant_hombres', models.IntegerField()),
                ('cant_mujeres', models.IntegerField()),
                ('tema_central', models.CharField(max_length=255)),
                ('subtema', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('tiempo', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='creciendosanocrud.MetaModelo')),
            ],
            options={
                'db_table': 'eventos',
                'ordering': ['-id'],
            },
        ),
    ]
